### ISSUE TITLE
Zeros in the temperature introduced along MPI boundaries after adding material

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#212]
Every time that material is added in an MPI run, zeros are introduced along the MPI domain boundaries. At first I assumed this was a ghost cell issue, but adding a simple `temperature.update_ghost_values()` after the call to `add_material` doesn't do anything. I'm not sure when this started happening.

@Rombur, I can keep digging, but if it's obvious to you what's wrong, let me know.

**Comment by stvdwtt** [comment]
Inputs:
[mpi_zeros_inputs.zip](https://github.com/adamantine-sim/adamantine/files/10540343/mpi_zeros_inputs.zip)

Temperature:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/10517751/215606452-9a84d0b9-3093-44e3-8f37-7817561013b3.png">

MPI domains:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/10517751/215606518-f6a8ea59-9a96-4f9d-a774-6d6ebe8cbe4a.png">

**Comment by Rombur** [comment]
The problem is from https://github.com/adamantine-sim/adamantine/blob/a9c99e22cf1eaad22cd22c63119276f302607ec9/source/ThermalPhysics.templates.hh#L844
If `rw_solution` contains a zero it will override the value and you will see it. 

Under the following code https://github.com/adamantine-sim/adamantine/blob/a9c99e22cf1eaad22cd22c63119276f302607ec9/source/ThermalPhysics.templates.hh#L783-L787

Can you set the value of the ghosted elements to `std::numeric_limits<double>::infinity()`
